name: push dockerhub

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.yaml'
      - 'Dockerfile'
      - 'src/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull sources'
        uses: actions/checkout@v4

      - name: 'Set up Rust'
        uses: dtolnay/rust-toolchain@stable

      - name: 'Test'
        timeout-minutes: 5
        run: cargo test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LINK_SHORTER_DOCKERHUB_USERNAME }}
          password: ${{ secrets.LINK_SHORTER_DOCKERHUB }}

      - name: Build and push
        if: "!startsWith(github.ref, 'refs/tags')"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: lazymio/link-shorter-rs:latest
      
      - name: Build and push with github ref
        if: "startsWith(github.ref, 'refs/tags')"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            lazymio/link-shorter-rs:latest
            lazymio/link-shorter-rs:${{github.ref_name}}